import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('catálogos por salão, criação automática, histórico e proteção contra itens livres',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public to authenticated;grant execute on function auth.uid() to authenticated;`);
 await db.exec(await readFile(new URL('../supabase/001_estrutura.sql',import.meta.url),'utf8'));
 const saloes=(await db.query('select * from saloes order by nome')).rows;
 const [a,b]=saloes.map(s=>s.id),user='00000000-0000-4000-8000-000000000001';
 await db.exec(`insert into auth.users values ('${user}');insert into membros values ('${user}','${a}','gerente');insert into eventos(salao_id,cliente,data) values ('${a}','Anterior','2027-01-01');`);
 const anterior=(await db.query('select id from eventos')).rows[0].id;
 await db.exec(`insert into itens_evento(evento_id,salao_id,descricao,categoria,quantidade,valor_unitario) values ('${anterior}','${a}','Pacote','pacote',1,1000)`);
 await db.exec(await readFile(new URL('../supabase/002_catalogos.sql',import.meta.url),'utf8'));
 assert.equal((await db.query(`select * from itens_evento where evento_id='${anterior}' and descricao='Pacote'`)).rows.length,1);
 assert.equal(Number((await db.query(`select sum(total) as total from itens_evento where evento_id='${anterior}'`)).rows[0].total),1000);
 for(const [id,count] of [[a,17],[b,15]])assert.equal((await db.query(`select * from catalogo_salao where salao_id='${id}' and tipo='servico'`)).rows.length,count);
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${user}';`);
 const novo=(await db.query(`insert into eventos(salao_id,cliente,data) values ('${a}','Novo','2027-02-01') returning id`)).rows[0].id;
 assert.equal((await db.query(`select * from itens_evento where evento_id='${novo}'`)).rows.length,17);
 assert.equal((await db.query(`select * from tarefas where evento_id='${novo}'`)).rows.length,12);
 await assert.rejects(db.exec(`insert into itens_evento(evento_id,salao_id,descricao,categoria,valor_unitario) values ('${novo}','${a}','Livre','extra',100)`));
 await assert.rejects(db.exec(`insert into tarefas(evento_id,salao_id,titulo) values ('${novo}','${a}','Livre')`));
 await assert.rejects(db.exec(`insert into catalogo_salao(salao_id,tipo,nome) values ('${b}','tarefa','Inválida')`));
 const item=(await db.query(`select * from itens_evento where evento_id='${novo}' and unidade='pessoas'`)).rows[0];
 await db.exec(`update itens_evento set quantidade=3,valor_unitario=140,descricao='Nome livre' where id='${item.id}'`);
 const updated=(await db.query(`select * from itens_evento where id='${item.id}'`)).rows[0];
 assert.equal(Number(updated.total),420);assert.equal(updated.descricao,item.descricao);
 await db.exec(`update catalogo_salao set ativo=false where id='${item.catalogo_id}'; insert into catalogo_salao(salao_id,tipo,nome) values ('${a}','tarefa','Nova etapa')`);
 const futuro=(await db.query(`insert into eventos(salao_id,cliente,data) values ('${a}','Futuro','2027-03-01') returning id`)).rows[0].id;
 assert.equal((await db.query(`select * from itens_evento where evento_id='${futuro}'`)).rows.length,16);
 assert.equal((await db.query(`select * from tarefas where evento_id='${futuro}'`)).rows.length,13);
 assert.equal((await db.query(`select * from tarefas where evento_id='${novo}'`)).rows.length,12);
 await db.exec(`update itens_evento set valor_unitario=150 where id='${item.id}'`);
 await db.exec('reset role');
 await db.exec(await readFile(new URL('../supabase/003_tipos_evento.sql',import.meta.url),'utf8'));
 await db.exec(`set role authenticated;set request.jwt.claim.sub='${user}';`);
 await assert.rejects(db.exec(`insert into eventos(salao_id,cliente,data,tipo) values ('${a}','Teste','2027-04-01','Livre')`));
 const tipado=(await db.query(`insert into eventos(salao_id,cliente,data,tipo) values ('${a}','Teste','2027-04-01','15 Anos') returning id`)).rows[0].id;
 await db.exec(`update catalogo_salao set ativo=false where salao_id='${a}' and tipo='tipo_evento' and nome='15 Anos'`);
 await db.exec(`update eventos set cliente='Nome atualizado' where id='${tipado}'`);
 await assert.rejects(db.exec(`insert into eventos(salao_id,cliente,data,tipo) values ('${a}','Teste','2027-04-01','15 Anos')`));
 await db.exec(`insert into catalogo_salao(salao_id,tipo,nome) values ('${a}','tipo_evento','Corporativo')`);
 await db.exec(`update eventos set tipo='Corporativo' where id='${tipado}'`);
 await db.exec('reset role');
 await db.exec(await readFile(new URL('../supabase/004_cancelar_excluir.sql',import.meta.url),'utf8'));
 const secretary='00000000-0000-4000-8000-000000000002';
 await db.exec(`insert into auth.users values ('${secretary}');insert into membros values ('${secretary}','${a}','secretaria');set role authenticated;set request.jwt.claim.sub='${user}';`);
 await assert.rejects(db.exec(`update eventos set status='cancelado' where id='${tipado}'`));
 await assert.rejects(db.exec(`update eventos set status='cancelado',cancelamento_justificativa='   ' where id='${tipado}'`));
 await db.exec(`update eventos set status='cancelado',cancelamento_justificativa='Solicitado pelo cliente' where id='${tipado}'`);
 const canceled=(await db.query(`select * from eventos where id='${tipado}'`)).rows[0];
 assert.equal(canceled.status,'cancelado');assert.equal(canceled.cancelado_por,user);assert.ok(canceled.cancelado_em);
 await db.exec(`insert into pagamentos(evento_id,salao_id,data,valor) values ('${tipado}','${a}','2027-01-01',500)`);
 await db.exec(`set request.jwt.claim.sub='${secretary}'`);
 await assert.rejects(db.exec(`select public.excluir_evento('${tipado}')`));
 await db.exec(`set request.jwt.claim.sub='${user}';select public.excluir_evento('${tipado}')`);
 assert.equal((await db.query(`select * from eventos where id='${tipado}'`)).rows.length,0);
 for(const table of ['itens_evento','pagamentos','tarefas'])assert.equal((await db.query(`select * from ${table} where evento_id='${tipado}'`)).rows.length,0);
 assert.equal((await db.query(`select * from eventos where id='${novo}'`)).rows.length,1);
 }finally{await db.close()}
});
