import React,{useState} from 'react';
import {filtrarEventos,hojeSP} from './agenda.mjs';
import {formatDate} from './dates.mjs';
export default function Agenda({eventos,loading,onOpen}){
 const [periodo,P]=useState('proximos'),[busca,B]=useState(''),[mes,M]=useState(hojeSP().slice(0,7)),[dia,D]=useState(''),[monthOnly,MO]=useState(false);
 const filtered=filtrarEventos(eventos,periodo,busca),list=dia?filtered.filter(e=>e.data===dia):monthOnly?filtered.filter(e=>e.data.startsWith(mes)):filtered;
 const [y,m]=mes.split('-').map(Number),first=new Date(y,m-1,1).getDay(),days=new Date(y,m,0).getDate();
 function move(n){const d=new Date(y,m-1+n,1);M(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);D('')}
 return <><section className="card agenda-controls"><div className="fields"><label>Mostrar eventos<select value={periodo} onChange={e=>{P(e.target.value);D('');MO(false)}}><option value="proximos">Hoje e próximos eventos</option><option value="passados">Eventos passados</option><option value="todos">Todos os eventos</option></select></label><label>Buscar<input placeholder="Cliente ou tipo de evento" value={busca} onChange={e=>{B(e.target.value);D('')}}/></label></div></section>
 <div className="agenda-layout"><section className="card agenda-calendar"><h2>Calendário</h2><div className="calendar-heading"><button className="back" aria-label="Mês anterior" onClick={()=>move(-1)}>‹</button><label>Mês<input aria-label="Mês do calendário" type="month" value={mes} onChange={e=>{if(e.target.value){M(e.target.value);D('')}}}/></label><button className="back" aria-label="Próximo mês" onClick={()=>move(1)}>›</button></div><div className="calendar-grid">{['D','S','T','Q','Q','S','S'].map((v,i)=><small key={i}>{v}</small>)}{Array.from({length:first},(_,i)=><span key={`empty${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${mes}-${String(i+1).padStart(2,'0')}`,events=filtered.filter(e=>e.data===date);return <button key={date} className={events.length?'has-events':''} aria-label={`${formatDate(date)}: ${events.length} evento(s)`} aria-pressed={dia===date} onClick={()=>{D(date);if(events.length===1)onOpen(events[0])}}>{i+1}{events.length>0&&<span className="event-dot">{events.length}</span>}</button>})}</div><p className="calendar-help">Os dias destacados possuem eventos.</p><div className="calendar-actions"><button className="back" onClick={()=>{MO(true);D('');P('todos')}}>Exibir eventos deste mês</button><button className="back" onClick={()=>{MO(false);D('');P('todos')}}>Exibir todos os eventos</button></div></section>
 <section className="card"><div className="toolbar"><h2>{dia?formatDate(dia):monthOnly?'Eventos do mês':'Eventos'} <small>({list.length})</small></h2>{dia&&<button className="back" onClick={()=>D('')}>Limpar dia</button>}</div>{loading?<p>Carregando eventos…</p>:list.length?<div className="event-list">{list.map(ev=><article key={ev.id}><time>{formatDate(ev.data)}</time><div><h3>{ev.cliente}</h3><p>{ev.tipo||'Tipo não informado'} · {ev.convidados??'—'} convidados</p></div><span className="badge">{ev.status}</span><button className="open-event" onClick={()=>onOpen(ev)}>Abrir evento</button></article>)}</div>:<p className="empty">Nenhum evento neste filtro.</p>}</section></div></>
}
