import ConfigSaloes from './ConfigSaloes.jsx';
import React,{useEffect,useState} from 'react';
const tipos={saloes:'Sal?es',servico:'Serviços',tarefa:'Tarefas',tipo_evento:'Tipos de evento',detalhe:'Detalhes',profissional:'Profissionais'};
export default function Catalogos({db,saloes,onClose,onLockChange,onSalaoUpdate}){
 const [childLocked,CL]=useState(false);
 const [rows,R]=useState([]),[tipo,T]=useState('servico'),[editing,ED]=useState(null),[busy,B]=useState(false),[error,E]=useState(''),[loaded,L]=useState(false),[version,V]=useState(0),[remove,RM]=useState(null),[dirty,D]=useState(false);
 useEffect(()=>{onLockChange?.(dirty||busy||childLocked);return()=>onLockChange?.(false)},[dirty,busy,childLocked]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 async function load(){const {data,error}=await db.from('configuracoes_catalogo').select('*, catalogo_salao(salao_id,ativo)').order('ordem').order('nome');if(error)throw error;R(data);L(true)}
 useEffect(()=>{load().catch(()=>E('É necessário aplicar a atualização 005 do banco para usar as configurações gerais.'))},[]);
 function leave(action){if(dirty&&!window.confirm('Descartar as alterações ainda não salvas deste cadastro?'))return;D(false);ED(null);V(v=>v+1);action()}
 async function salvar(e){e.preventDefault();const f=new FormData(e.currentTarget),selecionados=f.getAll('saloes');if(!selecionados.length){E('Selecione pelo menos um salão.');return}if(tipo==='profissional'&&!f.getAll('servicos').length){E('Selecione Fotos e/ou Filmagem.');return}B(true);E('');try{const {error}=await db.rpc('salvar_configuracao',{p_id:editing?.id||null,p_tipo:tipo,p_nome:f.get('nome').trim(),p_unidade:tipo==='servico'?f.get('unidade'):'item',p_campo_tipo:tipo==='detalhe'?f.get('campo_tipo'):'texto',p_servicos:tipo==='profissional'?f.getAll('servicos'):[],p_saloes:selecionados});if(error)throw error;D(false);ED(null);V(v=>v+1);await load()}catch{E('Não foi possível salvar. Confira o nome, os salões e suas permissões. Não use um nome já cadastrado no mesmo salão.')}finally{B(false)}}
 async function excluir(){B(true);E('');try{const {error}=await db.rpc('excluir_configuracao',{p_id:remove.id});if(error)throw error;RM(null);await load()}catch{E('Não foi possível excluir o cadastro.')}finally{B(false)}}
 return <section><button className="back" disabled={busy||childLocked} onClick={()=>leave(onClose)}>← Voltar aos eventos</button><h1>Configurações gerais</h1><p>Cadastre uma vez e selecione os salões em que o item ficará disponível. Eventos já criados preservam seus itens e valores.</p><nav className="detail-tabs" aria-label="Cadastros">{Object.entries(tipos).map(([id,label])=><button key={id} disabled={busy||childLocked} onClick={()=>leave(()=>{T(id);RM(null)})} aria-current={tipo===id?'page':undefined}>{label}</button>)}</nav>{error&&<p role="alert" className="error">{error}</p>}{tipo==='saloes'?<ConfigSaloes db={db} saloes={saloes} onUpdate={onSalaoUpdate} onLockChange={CL}/>:loaded&&<>
 {tipo==='servico'&&<section className="card"><h2>Pacote</h2><p>Obrigatório em todos os eventos. O valor é definido na ficha do evento; este item não pode ser alterado ou excluído do cadastro.</p></section>}
 {tipo==='profissional'&&<p>“Particular” estará sempre disponível nas opções de Fotos e Filmagem.</p>}
 <form className="card" onSubmit={salvar} onChange={()=>D(true)} key={`${tipo}-${editing?.id||'novo'}-${version}`}><h2>{editing?'Editar cadastro':'Adicionar cadastro'}</h2><fieldset disabled={busy}><div className="fields"><label>Nome<input name="nome" required maxLength="150" defaultValue={editing?.nome||''}/></label>{tipo==='servico'&&<label>Quantidade medida em<select name="unidade" defaultValue={editing?.unidade||'item'}><option value="item">Item (valor total)</option><option value="litros">Litros</option><option value="pessoas">Pessoas</option></select></label>}{tipo==='detalhe'&&<label>Como preencher<select name="campo_tipo" defaultValue={editing?.campo_tipo||'texto'}><option value="texto">Digitar texto</option><option value="checkbox">Assinalar (sim/não)</option></select></label>}</div>{tipo==='profissional'&&<fieldset className="choice-group"><legend>Serviços prestados</legend>{['Fotos','Filmagem'].map(s=><label className="task" key={s}><input type="checkbox" name="servicos" value={s} defaultChecked={editing?.servicos?.includes(s)}/>{s}</label>)}</fieldset>}<fieldset className="choice-group"><legend>Disponível nos salões</legend>{saloes.map(s=><label className="task" key={s.id}><input type="checkbox" name="saloes" value={s.id} defaultChecked={editing?.catalogo_salao?.some(c=>c.salao_id===s.id&&c.ativo)||false}/>{s.nome}</label>)}</fieldset><div className="actions"><button>{busy?'Salvando…':editing?'Salvar alterações':'Cadastrar'}</button>{(editing||dirty)&&<button type="button" className="back" onClick={()=>leave(()=>{})}>Cancelar edição</button>}</div></fieldset></form>
 {remove&&<section className="card" role="alert"><h2>Excluir “{remove.nome}”?</h2><p>O item deixará de aparecer nos novos eventos dos salões vinculados. Os registros dos eventos existentes serão preservados.</p><div className="actions"><button className="danger" disabled={busy} onClick={excluir}>Confirmar exclusão</button><button className="back" disabled={busy} onClick={()=>RM(null)}>Voltar</button></div></section>}
 <section className="card">{rows.filter(r=>r.tipo===tipo&&!r.obrigatorio).map(r=><article className="record" key={r.id}><div><h3>{r.nome}</h3><small>{saloes.filter(s=>r.catalogo_salao?.some(c=>c.salao_id===s.id&&c.ativo)).map(s=>s.nome).join(' · ')||'Sem salão ativo'}{tipo==='profissional'?` · ${r.servicos.join(' / ')}`:tipo==='detalhe'?` · ${r.campo_tipo==='checkbox'?'Assinalar':'Texto'}`:''}</small></div><div className="actions"><button className="back" disabled={busy||childLocked} onClick={()=>leave(()=>{ED(r);RM(null);window.scrollTo({top:0,behavior:'smooth'})})}>Editar</button><button className="danger" disabled={busy} onClick={()=>RM(r)}>Excluir</button></div></article>)}</section></>}</section>
}
