import React,{useEffect,useState} from 'react';
const defaults={itens:false,valores:false,pagamentos:false,detalhes:false,checklist:false,progresso:true,contador:true,animacao:true};
const labels={itens:'Itens contratados (serviços com valor maior que zero)',valores:'Valores dos serviços e resumo financeiro',pagamentos:'Histórico de pagamentos e devoluções, com valores',detalhes:'Detalhes da festa — textos e opções assinaladas',checklist:'Checklist completo com nomes das tarefas',progresso:'Progresso geral da preparação',contador:'Contagem regressiva para o evento',animacao:'Animação de boas-vindas com o contador'};
export default function ConfigPortal({db,saloes,onLockChange}){
 const [sid,S]=useState(saloes[0]?.id||''),[draft,D]=useState(defaults),[saved,SV]=useState(defaults),[busy,B]=useState(false),[loading,L]=useState(true),[dirty,DI]=useState(false),[error,E]=useState(''),[notice,N]=useState('');
 useEffect(()=>{onLockChange?.(dirty||busy);return()=>onLockChange?.(false)},[dirty,busy]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 useEffect(()=>{let active=true;L(true);E('');N('');db.from('portal_config').select('*').eq('salao_id',sid).maybeSingle().then(({data,error})=>{if(!active)return;if(error)E('Aplique a atualização 011 para configurar o portal.');else{const v={...defaults,...data};D(v);SV(v)}L(false)});return()=>{active=false}},[sid]);
 async function save(e){e.preventDefault();B(true);E('');N('');try{const payload={salao_id:sid,...Object.fromEntries(Object.keys(defaults).map(k=>[k,draft[k]]))};const r=await db.from('portal_config').upsert(payload);if(r.error)throw r.error;SV(draft);DI(false);N('Portal atualizado. O cliente verá as opções ao entrar ou atualizar o andamento.')}catch{E('Não foi possível salvar as opções do portal.')}finally{B(false)}}
 return <section className="card"><h2>Portal do cliente</h2><p>Defina o que os clientes deste salão podem consultar. Cada pessoa continua acessando somente o próprio evento.</p><label>Salão<select value={sid} disabled={dirty||busy} onChange={e=>S(e.target.value)}>{saloes.map(s=><option value={s.id} key={s.id}>{s.nome}</option>)}</select></label>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}{loading?<p>Carregando opções…</p>:<form onSubmit={save}><fieldset disabled={busy}>{Object.entries(labels).map(([k,label])=><label className="task" key={k}><input type="checkbox" checked={draft[k]} onChange={e=>{D({...draft,[k]:e.target.checked});DI(true);N('')}}/>{label}</label>)}<p>Ao liberar detalhes e checklist, seus textos ficam visíveis ao cliente. Observações internas do evento e dos pagamentos não são compartilhadas. O histórico de pagamentos exibe valores mesmo com o resumo financeiro desmarcado.</p><div className="actions"><button disabled={!dirty}>Salvar opções</button><button type="button" className="back" disabled={!dirty} onClick={()=>{D(saved);DI(false)}}>Cancelar</button></div></fieldset></form>}</section>;
}
