import React,{useEffect,useState} from 'react';
import {temas,temaDoSalao,estiloTema} from './themes.mjs';
export default function ConfigSaloes({db,saloes,onUpdate,onLockChange}){
 const [id,ID]=useState(saloes[0]?.id||''),[theme,TH]=useState(temaDoSalao(saloes[0])),[busy,B]=useState(false),[error,E]=useState(''),[saved,S]=useState(false);
 const selected=saloes.find(s=>s.id===id),dirty=theme!==temaDoSalao(selected);
 useEffect(()=>{onLockChange?.(dirty||busy);return()=>onLockChange?.(false)},[dirty,busy]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 async function save(e){e.preventDefault();B(true);E('');S(false);try{const {data,error}=await db.from('saloes').update({tema:theme}).eq('id',id).select().single();if(error)throw error;onUpdate(data);S(true)}catch{E('Não foi possível salvar o tema. Confira se a atualização 006 foi aplicada e tente novamente.')}finally{B(false)}}
 return <section className="card"><h2>Dados do salão</h2><label>Salão<select value={id} disabled={busy||dirty} onChange={e=>{ID(e.target.value);TH(temaDoSalao(saloes.find(s=>s.id===e.target.value)));S(false);E('')}}>{saloes.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><form onSubmit={save}><fieldset disabled={busy}><legend>Tema do salão</legend><div className="theme-options">{Object.entries(temas).map(([key,t])=><label className="theme-option" key={key}><input type="radio" name="tema" value={key} checked={theme===key} onChange={()=>{TH(key);S(false)}}/><span className="theme-swatch" style={{background:t.principal}}/>{t.nome}</label>)}</div><div className="theme-preview" style={estiloTema(theme)}><span>{selected?.nome}</span><strong>Agenda de eventos</strong><p>Prévia das cores do salão</p><span className="preview-button">Novo evento</span></div><div className="actions"><button disabled={!dirty||busy}>{busy?'Salvando…':'Salvar tema'}</button><button type="button" className="back" disabled={!dirty||busy} onClick={()=>{TH(temaDoSalao(selected));E('');S(false)}}>Cancelar alteração</button></div></fieldset></form>{error&&<p className="error" role="alert">{error}</p>}{saved&&<p className="success" role="status">Tema salvo para este salão.</p>}</section>;
}
