import TelefoneInput from './TelefoneInput.jsx';
import React,{useEffect,useState} from 'react';
import {temas,temaDoSalao,estiloTema} from './themes.mjs';
const fields={nome:'Nome do salão',slogan:'Slogan do salão (opcional)',endereco:'Endereço',cnpj:'CNPJ',telefone:'Telefone',email:'E-mail'};
export default function IdentidadeSalao({db,saloes,onUpdate,onLockChange}){
 const [id,ID]=useState(saloes[0]?.id||''),[draft,D]=useState({...saloes[0]}),[dirty,DI]=useState(false),[busy,B]=useState(false),[error,E]=useState(''),[saved,S]=useState(false);
 useEffect(()=>{onLockChange?.(dirty||busy);return()=>onLockChange?.(false)},[dirty,busy]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 function change(k,v){D(old=>({...old,[k]:v}));DI(true);S(false)}
 async function logo(file){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>8*1024*1024){E('Selecione PNG ou JPG de até 8 MB.');return}B(true);E('');let url;try{url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,800/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL(file.type,.85);if(data.length>=1200000)throw Error();change('logo',data)}catch{E('Não foi possível carregar esse logo. Use uma imagem menor.')}finally{if(url)URL.revokeObjectURL(url);B(false)}}
 async function save(e){e.preventDefault();B(true);E('');S(false);try{const payload=Object.fromEntries(Object.keys(fields).map(k=>[k,(draft[k]||'').trim()]));payload.tema=temaDoSalao(draft);payload.logo=draft.logo||'';const {data,error}=await db.from('saloes').update(payload).eq('id',id).select().single();if(error)throw error;D(data);DI(false);onUpdate(data);S(true)}catch{E('Não foi possível salvar. Confira se a atualização 016 foi aplicada.')}finally{B(false)}}
 return <section className="card"><h2>Dados do salão</h2><label>Salão<select disabled={busy||dirty} value={id} onChange={e=>{ID(e.target.value);D({...saloes.find(s=>s.id===e.target.value)});S(false)}}>{saloes.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><form onSubmit={save}><fieldset disabled={busy}><div className="fields">{Object.entries(fields).map(([k,title])=><label key={k}>{title}{k==='telefone'?<TelefoneInput value={draft[k]||''} onChange={v=>change(k,v)}/>:<input maxLength={k==='slogan'?180:undefined} required={k==='nome'} type={k==='email'?'email':'text'} value={draft[k]||''} onChange={e=>change(k,e.target.value)}/>}</label>)}</div><label>Logo do salão (PNG ou JPG)<input type="file" accept="image/png,image/jpeg" onChange={e=>logo(e.target.files[0])}/></label>{draft.logo&&<div className="logo-preview"><img src={draft.logo} alt={draft.nome}/><button type="button" className="back" onClick={()=>change('logo','')}>Remover logo</button></div>}<h3>Tema</h3><div className="theme-options">{Object.entries(temas).map(([k,t])=><label className="theme-option" key={k}><input type="radio" checked={temaDoSalao(draft)===k} onChange={()=>change('tema',k)}/><span className="theme-swatch" style={{background:t.principal}}/>{t.nome}</label>)}</div><div className="theme-preview" style={estiloTema(temaDoSalao(draft))}><strong>{draft.nome}</strong><p>Prévia do tema do salão</p></div><div className="actions"><button disabled={!dirty}>{busy?'Salvando…':'Salvar dados'}</button><button type="button" disabled={!dirty} className="back" onClick={()=>{D({...saloes.find(s=>s.id===id)});DI(false);S(false);E('')}}>Cancelar alteração</button></div></fieldset></form>{error&&<p className="error" role="alert">{error}</p>}{saved&&<p className="success" role="status">Dados do salão salvos.</p>}</section>
}
