import React,{useState} from 'react';
export default function Login({db}){
 const [mode,M]=useState('login'),[busy,B]=useState(false),[error,E]=useState(''),[notice,N]=useState('');
 async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);B(true);E('');N('');try{
  const email=f.get('email').trim(),password=f.get('senha');
  if(mode==='forgot'){const r=await db.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/?recuperar=1'});if(r.error)throw Error('Não foi possível solicitar o e-mail. Aguarde um minuto e tente novamente.');N('Se houver uma conta com esse e-mail, você receberá um link para definir uma nova senha. Confira também o spam.');return}
  if(mode==='signup'&&password!==f.get('confirmar'))throw Error('As senhas precisam ser iguais.');
  const result=mode==='signup'?await db.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}}):await db.auth.signInWithPassword({email,password});
  if(result.error)throw Error(mode==='signup'?'Não foi possível criar a conta. Se já possui senha, use Entrar.':'Confira seu e-mail e senha.');
  if(mode==='signup'&&!result.data.session)N('Confira seu e-mail para confirmar o cadastro. O acesso aos salões depende da autorização da administração.');
 }catch(err){E(err.message||'Não foi possível conectar. Tente novamente.')}finally{B(false)}}
 return <main className="login"><section className="brand"><span className="eyebrow">EXXCELÊNCIA · EXXPLÊNDIDO</span><h1>Cada detalhe.<br/>Um grande evento.</h1></section><section className="login-card"><span className="eyebrow">GESTÃO DE EVENTOS</span><h2>{mode==='forgot'?'Recuperar senha':mode==='signup'?'Criar minha senha':'Bem-vinda de volta'}</h2><p>{mode==='forgot'?'Informe seu e-mail para receber o link de recuperação.':mode==='signup'?'Use o mesmo e-mail autorizado pela administração.':'Entre com seu acesso autorizado.'}</p><form onSubmit={submit}><fieldset disabled={busy}><label>E-mail<input name="email" type="email" autoComplete="username" required/></label>{mode!=='forgot'&&<label>Senha<input name="senha" type="password" minLength={mode==='signup'?8:undefined} autoComplete={mode==='signup'?'new-password':'current-password'} required/></label>}{mode==='signup'&&<label>Confirmar senha<input name="confirmar" type="password" autoComplete="new-password" required/></label>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}<button>{busy?'Aguarde…':mode==='forgot'?'Enviar link de recuperação':mode==='signup'?'Criar minha senha':'Entrar no salão'}</button></fieldset></form><button className="back" disabled={busy} onClick={()=>{M(mode==='login'?'signup':'login');E('');N('')}}>{mode!=='login'?'Voltar para entrar':'Primeiro acesso · Criar minha senha'}</button>{mode==='login'&&<button className="back" disabled={busy} onClick={()=>{M('forgot');E('');N('')}}>Esqueci minha senha</button>}</section></main>
}
