import React,{useEffect,useState} from 'react';
const tables={eventos:'Eventos',itens_evento:'Serviços contratados',pagamentos:'Pagamentos',tarefas:'Tarefas',detalhes_evento:'Detalhes',saloes:'Salões',membros:'Vínculos de usuários',acessos_autorizados:'Autorizações',acessos_clientes:'Acessos de clientes',perfis_acesso:'Perfis de acesso',configuracoes_catalogo:'Cadastros gerais',catalogo_salao:'Cadastros por salão',portal_config:'Portal do cliente',perfil_pessoal:'Perfil pessoal'};
const actions={INSERT:'Criação',UPDATE:'Alteração',DELETE:'Exclusão'};
const time=v=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'medium',timeZone:'America/Sao_Paulo'}).format(new Date(v));
const value=v=>v===undefined?'—':v===null?'Vazio':typeof v==='object'?JSON.stringify(v,null,2):String(v);
export default function Logs({db,saloes}){
 const [rows,R]=useState([]),[page,P]=useState(0),[sid,S]=useState(''),[table,T]=useState(''),[busy,B]=useState(true),[error,E]=useState(''),[refresh,V]=useState(0);
 useEffect(()=>{let active=true;B(true);E('');let q=db.from('logs_alteracoes').select('*').order('criado_em',{ascending:false}).order('id',{ascending:false});if(sid)q=q.eq('salao_id',sid);if(table)q=q.eq('tabela',table);q.range(page*50,page*50+50).then(({data,error})=>{if(!active)return;if(error){E('Não foi possível carregar os logs. Confira a atualização 013 e seu acesso administrativo.');R([])}else R(data||[]);B(false)});return()=>{active=false}},[sid,table,page,refresh]);
 return <section><h2>Logs de alterações</h2><p>Histórico a partir da atualização 013, com horário de Brasília. Operações sem uma sessão do aplicativo aparecem como “Sistema / SQL”. Senhas e logins são tratados pelo serviço de autenticação e não aparecem aqui.</p><div className="fields"><label>Salão<select value={sid} onChange={e=>{S(e.target.value);P(0)}}><option value="">Todos os autorizados e alterações gerais</option>{saloes.map(s=><option value={s.id} key={s.id}>{s.nome}</option>)}</select></label><label>Tipo de registro<select value={table} onChange={e=>{T(e.target.value);P(0)}}><option value="">Todos</option>{Object.entries(tables).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><button className="back" disabled={busy} onClick={()=>V(v=>v+1)}>Atualizar logs</button>{error&&<p role="alert" className="error">{error}</p>}{busy?<p>Carregando histórico…</p>:<section className="card audit-list">{!rows.length&&<p>Nenhuma alteração encontrada.</p>}{rows.slice(0,50).map(r=><article className="audit-row" key={r.id}><h3>{actions[r.acao]} · {tables[r.tabela]||r.tabela}</h3><p><strong>{r.autor}</strong>{r.autor_email?` (${r.autor_email})`:""} · {time(r.criado_em)}</p><p>{saloes.find(s=>s.id===r.salao_id)?.nome||'Configuração geral'} · Registro: {r.registro}</p><details><summary>Ver campos alterados ({r.campos.length})</summary>{r.campos.map(k=><div className="audit-change" key={k}><strong>{k}</strong><div><small>Antes</small><pre>{value(r.antes?.[k])}</pre></div><div><small>Depois</small><pre>{value(r.depois?.[k])}</pre></div></div>)}</details></article>)}</section>}<div className="actions"><button className="back" disabled={busy||page===0} onClick={()=>P(p=>p-1)}>Anterior</button><span>Página {page+1}</span><button className="back" disabled={busy||rows.length<=50} onClick={()=>P(p=>p+1)}>Próxima</button></div></section>;
}
