import React,{useEffect,useRef,useState} from 'react';
import MinhaSenha from './MinhaSenha.jsx';
export default function MinhaConta({db,perfil,onUpdate,onClose,onLockChange}){
 const [nome,N]=useState(perfil?.nome||''),[foto,F]=useState(perfil?.foto||''),[dirty,D]=useState(false),[busy,B]=useState(false),[error,E]=useState(''),[ok,O]=useState(''),[senha,S]=useState(false);
 const heading=useRef(null);
 useEffect(()=>{heading.current?.focus()},[]);
 useEffect(()=>{onLockChange?.(dirty||busy);return()=>onLockChange?.(false)},[dirty,busy]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 function close(){if(dirty&&!window.confirm('Descartar as alterações não salvas do perfil?'))return;onClose()}
 async function photo(file){if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>8*1024*1024){E('Selecione JPG ou PNG de até 8 MB.');return}B(true);E('');let url;try{url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const size=Math.min(img.width,img.height);canvas.getContext('2d').drawImage(img,(img.width-size)/2,(img.height-size)/2,size,size,0,0,256,256);const data=canvas.toDataURL('image/jpeg',.82);if(data.length>150000)throw Error();F(data);D(true);O('')}catch{E('Não foi possível carregar a foto. Escolha outra imagem.')}finally{if(url)URL.revokeObjectURL(url);B(false)}}
 async function save(e){e.preventDefault();B(true);E('');O('');try{const r=await db.rpc('salvar_meu_perfil',{p_nome:nome,p_foto:foto});if(r.error||!r.data)throw Error();onUpdate?.(r.data);D(false);O('Perfil atualizado.')}catch{E('Não foi possível salvar. Confira a atualização 013 e tente novamente.')}finally{B(false)}}
 return <section><button className="back" disabled={busy} onClick={close}>Voltar</button><h1 ref={heading} tabIndex={-1}>Minha conta</h1><p>{perfil?.email}</p><section className="card profile-card"><form onSubmit={save}><fieldset disabled={busy}><h2>Meu perfil</h2><div className="account-photo">{foto?<img src={foto} alt="Sua foto"/>:<span aria-hidden="true">{(nome||'?').slice(0,1).toUpperCase()}</span>}</div><label>Nome de exibição<input required maxLength={120} value={nome} readOnly={!!perfil?.nome_cadastro} onChange={e=>{N(e.target.value);D(true);O('')}}/></label><label>Adicionar ou alterar foto<input type="file" accept="image/png,image/jpeg" onChange={e=>photo(e.target.files[0])}/></label>{foto&&<button type="button" className="back" onClick={()=>{F('');D(true)}}>Remover foto</button>}{error&&<p role="alert" className="error">{error}</p>}{ok&&<p role="status" className="success">{ok}</p>}<div className="actions"><button disabled={!dirty}>{busy?'Salvando…':'Salvar perfil'}</button><button type="button" className="back" disabled={!dirty} onClick={()=>{N(perfil?.nome||'');F(perfil?.foto||'');D(false);E('')}}>Cancelar alterações</button></div></fieldset></form><div className="profile-security">{senha?<MinhaSenha embedded db={db} onClose={()=>S(false)}/>:<button className="back" disabled={busy||dirty} onClick={()=>S(true)}>Alterar minha senha</button>}</div></section></section>;
}
