import React,{useEffect,useRef,useState} from 'react';
import {gruposPermissoes,camposPermissoes,novoPerfil,alterarPermissao} from './permissoes.mjs';
export default function Perfis({db,onLockChange,onUpdate}){
 const [rows,R]=useState([]),[draft,D]=useState(null),[busy,B]=useState(false),[dirty,DI]=useState(false),[error,E]=useState(''),[notice,N]=useState(''),[global,G]=useState(false),[loading,L]=useState(true);
 const title=useRef(null),newButton=useRef(null);
 useEffect(()=>{onLockChange?.(dirty||busy);return()=>onLockChange?.(false)},[dirty,busy]);
 useEffect(()=>{if(draft){title.current?.scrollIntoView?.({block:'start',behavior:'instant'});title.current?.focus({preventScroll:true})}},[draft?.codigo,!!draft]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 async function load(){const [a,b]=await Promise.all([db.from('perfis_acesso').select('*').order('nome'),db.rpc('administrador_global')]);if(a.error||b.error)throw Error();R(a.data);G(b.data);onUpdate?.(a.data)}
 useEffect(()=>{load().catch(()=>E('Não foi possível carregar os perfis. Confira a atualização 012 e a conexão.')).finally(()=>L(false))},[]);
 function edit(r){if(dirty&&!window.confirm('Descartar as alterações não salvas?'))return;D({...novoPerfil(),...r});DI(false);E('');N('')}
 function close(){if(dirty&&!window.confirm('Descartar as alterações não salvas?'))return;D(null);DI(false);E('');newButton.current?.focus()}
 async function save(e){e.preventDefault();B(true);E('');try{const r=await db.rpc('salvar_perfil_detalhado',{p_codigo:draft.codigo||null,p_nome:draft.nome,p_acessos:Object.fromEntries(camposPermissoes.map(k=>[k,!!draft[k]]))});if(r.error)throw r.error;const nome=draft.nome;D(null);DI(false);await load();N(`Perfil “${nome}” salvo.`);newButton.current?.focus()}catch(err){E(err.message||'Não foi possível salvar o perfil.')}finally{B(false)}}
 async function remove(r){if(!window.confirm(`Excluir o perfil ${r.nome}? Perfis em uso não podem ser excluídos.`))return;B(true);E('');try{const res=await db.rpc('excluir_perfil',{p_codigo:r.codigo});if(res.error)throw res.error;await load();N(`Perfil “${r.nome}” excluído.`)}catch(err){E(err.message||'Não foi possível excluir o perfil.')}finally{B(false)}}
 return <section><h2>Perfis de acesso</h2><p>Defina separadamente o que cada perfil pode visualizar e alterar nos salões autorizados.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}{loading?<p>Carregando perfis…</p>:!global?<p>Para alterar perfis gerais, é necessário administrar todos os salões.</p>:!draft&&<button ref={newButton} disabled={busy} onClick={()=>edit(novoPerfil())}>+ Novo perfil</button>}
 {global&&draft?<form className="card profile-editor" onSubmit={save} aria-labelledby="perfil-titulo"><fieldset disabled={busy}><div className="profile-editor-heading"><div><span className="eyebrow">{draft.codigo?'EDITANDO PERFIL':'NOVO CADASTRO'}</span><h3 id="perfil-titulo" ref={title} tabIndex={-1}>{draft.codigo?`Editar perfil: ${draft.nome}`:'Criar novo perfil'}</h3></div><button type="button" className="back" onClick={close}>Voltar à lista</button></div><label>Nome do perfil<input required maxLength={80} value={draft.nome} onChange={e=>{D({...draft,nome:e.target.value});DI(true)}}/></label><div className="permissions-grid">{gruposPermissoes.map(([group,items])=><fieldset className="permission-group" key={group}><legend>{group}</legend>{items.map(([k,label])=><label className="task" key={k}><input type="checkbox" checked={draft.administrar||!!draft[k]} disabled={draft.administrar&&k!=='administrar'} onChange={e=>{D(alterarPermissao(draft,k,e.target.checked));DI(true)}}/>{label}</label>)}</fieldset>)}</div><p>Permitir alterações habilita também a visualização correspondente. Ao retirar a visualização, os acessos dependentes são desmarcados. Administração completa libera todas as opções.</p><div className="actions save-bar"><button>{busy?'Salvando…':'Salvar perfil'}</button><button type="button" className="back" onClick={close}>Cancelar</button></div></fieldset></form>:<section className="card profile-list">{rows.map(r=><article className="record" key={r.codigo}><div><h3>{r.nome}</h3><p>{r.codigo==='cliente'?'Somente o próprio evento, conforme as opções do Portal do cliente':r.administrar?'Administração completa':gruposPermissoes.flatMap(([,items])=>items.filter(([k])=>r[k]).map(([,label])=>label)).join(' · ')||'Nenhum acesso aos eventos'}</p></div>{global&&!['gerente','cliente'].includes(r.codigo)?<div className="actions"><button className="back" disabled={busy} aria-label={`Editar perfil ${r.nome}`} onClick={()=>edit(r)}>Editar</button>{!r.sistema&&<button className="danger" disabled={busy} aria-label={`Excluir perfil ${r.nome}`} onClick={()=>remove(r)}>Excluir</button>}</div>:<small>Perfil reservado</small>}</article>)}</section>}
 </section>;
}
