import MinhaConta from './MinhaConta.jsx';
import Identificacao from './Identificacao.jsx';
import ContadorEvento from './ContadorEvento.jsx';
import {moeda} from './finance.mjs';
import React,{useEffect,useState} from 'react';
import {formatDate} from './dates.mjs';
import {estiloTema,temaDoSalao} from './themes.mjs';
export default function PortalCliente({db,perfil,onPerfilUpdate}){
 const [evento,E]=useState(null),[loading,L]=useState(true),[error,ER]=useState(''),[senha,S]=useState(false),[locked,LOCK]=useState(false);
 async function load(){L(true);ER('');try{const r=await db.rpc('meu_evento_resumido');if(r.error)throw r.error;E(r.data)}catch{E(null);ER('Não foi possível carregar o evento. Tente novamente.')}finally{L(false)}}
 useEffect(()=>{load()},[]);
 return <main className="client-portal app" style={estiloTema(temaDoSalao(evento))}><div className="client-inner"><header><div><span className="eyebrow">{evento?.salao||'GESTÃO DE EVENTOS'}</span><h1>Meu evento</h1></div><button className="back" disabled={locked} onClick={async()=>{const {error}=await db.auth.signOut();if(error)ER('Não foi possível sair.')}}>Sair</button></header>{evento&&<ContadorEvento evento={evento}/>} {senha?<MinhaConta db={db} perfil={perfil||{nome:evento?.cliente||'Minha conta'}} onUpdate={onPerfilUpdate} onLockChange={LOCK} onClose={()=>S(false)}/>:<><div className="client-account-toolbar"><Identificacao perfil={perfil} nome={evento?.cliente} onClick={()=>S(true)}/><button type="button" className="client-refresh" aria-label="Atualizar andamento" title="Atualizar andamento" disabled={loading} onClick={load}><span aria-hidden="true">↻</span><span>{loading?'Atualizando…':'Atualizar'}</span></button></div>{loading?<p>Carregando…</p>:error?<p role="alert" className="error">{error}</p>:evento?<><section className="card"><h2>{evento.cliente}</h2><dl className="read-fields">{[['Data',formatDate(evento.data)],['Celebração',evento.tipo],['Convidados',evento.convidados??'—'],['Situação',evento.status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{evento.tarefas_total!==undefined&&<><h3>Preparação do evento</h3><progress max={evento.tarefas_total||1} value={evento.tarefas_concluidas}/><p>{evento.tarefas_concluidas} de {evento.tarefas_total} etapas concluídas.</p></>}<small>Para combinar alterações, entre em contato com a administração do salão.</small></section>
 {evento.itens&&<section className="card"><h2>Itens contratados</h2>{!evento.itens.length&&<p>Nenhum item contratado disponível.</p>}{evento.itens.map((i,n)=><article className="record" key={n}><div><h3>{i.descricao}</h3><p>Quantidade: {i.quantidade}{i.unidade==='litros'?' litros':i.unidade==='pessoas'?' pessoas':''}</p></div>{i.total!==undefined&&<strong>{moeda(i.total)}</strong>}</article>)}</section>}
 {evento.financeiro&&<section className="card"><h2>Resumo financeiro</h2><dl className="read-fields">{[['Total contratado',evento.financeiro.contratado],['Pago (descontadas devoluções)',evento.financeiro.pago],[Number(evento.financeiro.contratado)-Number(evento.financeiro.pago)<0?'Crédito a seu favor':'Saldo a pagar',Math.abs(Number(evento.financeiro.contratado)-Number(evento.financeiro.pago))]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{moeda(v)}</dd></div>)}</dl></section>}
 {evento.pagamentos&&<section className="card"><h2>Pagamentos</h2>{!evento.pagamentos.length&&<p>Nenhum pagamento registrado.</p>}{evento.pagamentos.map((p,n)=><article className="record" key={n}><div><h3>{formatDate(p.data)}{p.natureza==='devolucao'?' · Devolução':''}</h3><p>{p.forma_pagamento||'Forma não informada'}</p></div><strong>{moeda((p.natureza==='devolucao'?-1:1)*Number(p.valor))}</strong></article>)}</section>}
 {evento.detalhes&&<section className="card"><h2>Detalhes da festa</h2><dl className="read-fields">{evento.detalhes.map((d,n)=><div key={n}><dt>{d.nome}</dt><dd>{d.campo_tipo==='checkbox'?(d.marcado?'Sim':'Não'):d.valor_texto||'—'}</dd></div>)}</dl></section>}
 {evento.tarefas&&<section className="card"><h2>Checklist da preparação</h2>{evento.tarefas.map((t,n)=><div className="task" key={n}><span aria-hidden="true">{t.concluida?'✓':'○'}</span><span>{t.titulo}<small>{t.concluida?'Concluída':'Pendente'}</small></span></div>)}</section>}
 </>:<section className="card"><h2>Acesso indisponível</h2><p>Seu evento ainda não foi vinculado ou o prazo de acompanhamento terminou. Consulte a administração.</p></section>}</>}</div></main>
}
