import {hojeSP} from './agenda.mjs';
import React,{useEffect,useState} from 'react';
import DataInput from './DataInput.jsx';
import {formatDate} from './dates.mjs';
const roles={gerente:'Gerente — administração e financeiro',dono:'Dono — consulta interna',secretaria:'Secretária — consulta interna',cliente:'Cliente — resumo do próprio evento'};
export default function Usuarios({db,saloes,onLockChange}){
 const [profiles,PF]=useState([]),[adding,A]=useState(false);
 useEffect(()=>{db.from('perfis_acesso').select('*').order('nome').then(({data})=>PF(data||[]))},[]);
 const roleLabels=profiles.length?Object.fromEntries(profiles.map(p=>[p.codigo,p.nome])):roles;
 const [expiry,EX]=useState(''),[rows,R]=useState([]),[events,EV]=useState([]),[editing,ED]=useState(null),[role,RO]=useState('secretaria'),[selected,SS]=useState([]),[busy,B]=useState(false),[dirty,D]=useState(false),[error,E]=useState(''),[notice,N]=useState(''),[version,V]=useState(0);
 useEffect(()=>{onLockChange?.(dirty||busy);return()=>onLockChange?.(false)},[dirty,busy]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 async function load(){const [a,b]=await Promise.all([db.rpc('listar_usuarios'),db.from('eventos').select('id,salao_id,cliente,data').in('salao_id',saloes.map(s=>s.id)).order('data')]);if(a.error||b.error)throw Error();R(a.data||[]);EV(b.data||[])}
 useEffect(()=>{load().catch(()=>E('Aplique a atualização 008 do banco para gerenciar estes acessos.'))},[]);
 function reset(r=null,newUser=false){if(dirty&&!window.confirm('Descartar alterações não salvas?'))return;A(newUser);E('');ED(r);EX(r?.validade||'');RO(r?.perfil||'secretaria');SS(r?.saloes||[]);D(false);V(v=>v+1)}
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget);if(role!=='cliente'&&!selected.length){E('Selecione pelo menos um salão.');return}B(true);E('');N('');try{
 const {error}=await db.rpc('salvar_usuario',{p_email:f.get('email').trim(),p_nome:f.get('nome').trim(),p_perfil:role,p_saloes:role==='cliente'?[]:selected,p_evento:role==='cliente'?f.get('evento'):null,p_ativo:f.has('ativo'),p_validade:f.get('validade')||null});if(error)throw error;
 D(false);ED(null);A(false);EX('');RO('secretaria');SS([]);V(v=>v+1);await load();N('Acesso salvo. A pessoa pode usar Criar minha senha na tela de entrada.');
 }catch(err){E(err.message?.includes('próprio acesso')?'Seu próprio acesso deve ser alterado por outro gerente.':'Não foi possível salvar. Confira o evento, os salões e suas permissões sobre os vínculos existentes.')}finally{B(false)}}
 const editor=(<form key={version} className="card" onSubmit={save} onChange={()=>D(true)}><fieldset disabled={busy}><h3>{editing?'Editar acesso':'Autorizar usuário'}</h3><div className="fields"><label>Nome<input name="nome" required defaultValue={editing?.nome||''}/></label><label>E-mail<input name="email" type="email" required readOnly={!!editing} defaultValue={editing?.email||''}/></label><label>Perfil<select value={role} onChange={e=>RO(e.target.value)}>{Object.entries(roleLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Acesso até (opcional)<DataInput name="validade" key={expiry} defaultValue={expiry} onValueChange={v=>{EX(v);D(true)}}/></label></div>
 {role==='cliente'?<label>Evento do cliente<select name="evento" required defaultValue={editing?.evento_id||''} onChange={e=>{const ev=events.find(x=>x.id===e.target.value);if(ev){const date=new Date(ev.data+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+1);EX(date.toISOString().slice(0,10))}}}><option value="">Selecione o evento</option>{events.filter(e=>e.data>=hojeSP()||e.id===editing?.evento_id).map(e=><option key={e.id} value={e.id}>{formatDate(e.data)} · {e.cliente} · {saloes.find(s=>s.id===e.salao_id)?.nome}</option>)}</select></label>:<fieldset className="choice-group"><legend>Salões permitidos</legend>{saloes.map(s=><label className="task" key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>SS(old=>e.target.checked?[...old,s.id]:old.filter(id=>id!==s.id))}/>{s.nome}</label>)}</fieldset>}
 <label className="task"><input type="checkbox" name="ativo" defaultChecked={editing?.ativo??true}/>Acesso ativo</label>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button>{busy?'Salvando…':'Salvar acesso'}</button><button type="button" className="back" onClick={()=>reset()}>Cancelar</button></div></fieldset></form>);
 return <section><h2>Usuários e acessos</h2><p>Escolha um ou dois salões para a equipe. Clientes veem as informações liberadas no Portal do cliente para o evento vinculado, até um dia após a festa ou a validade informada, o que ocorrer primeiro.</p>{error&&!editing&&!adding&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}
 <button className="back" disabled={busy} onClick={()=>reset(null,true)}>+ Novo usuário</button>{adding&&editor}

 <section className="card">{rows.map(r=><article className="record inline-record" key={r.email}><div><h3>{r.nome||r.email}</h3><p>{r.email} · {roleLabels[r.perfil]||r.perfil} · {r.ativo?'Ativo':'Suspenso'}</p><p>{r.perfil==='cliente'?events.find(e=>e.id===r.evento_id)?.cliente:saloes.filter(s=>r.saloes.includes(s.id)).map(s=>s.nome).join(' · ')}{r.validade?` · Até ${formatDate(r.validade)}`:''}</p></div><button className="back" disabled={busy} onClick={()=>reset(r)}>Editar / suspender</button>{editing?.email===r.email&&editor}</article>)}</section></section>
}
