import React,{useEffect,useState} from 'react';
import {prepararPDF} from './relatorios.mjs';
export default function VisualizarRelatorio({model,onClose}){
 const [blob,B]=useState(null),[error,E]=useState(''),[busy,S]=useState(true);
 useEffect(()=>{let active=true;S(true);B(null);E('');prepararPDF(model).then(doc=>{if(active){B(doc.output('blob'));S(false)}}).catch(()=>{if(active){E('Não foi possível gerar o PDF. Confira o logo do salão e tente novamente.');S(false)}});return()=>{active=false}},[model]);
 function open(){if(!blob)return;const url=URL.createObjectURL(blob);const win=window.open(url,'_blank');if(!win){URL.revokeObjectURL(url);E('Permita a abertura de uma nova aba para visualizar o PDF.')}}
 function download(){if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${model.title.replace(/[^\p{L}\p{N} -]/gu,'').slice(0,80)||'Evento'}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
 async function print(){const win=window.open('','_blank');if(!win){E('Permita abrir uma nova aba para imprimir.');return}try{const doc=await prepararPDF(model);doc.autoPrint();win.location.href=URL.createObjectURL(doc.output('blob'));}catch{win.close();E('Não foi possível abrir a impressão. Baixe o PDF e imprima pelo leitor.')}}
 const info=model.salaoInfo||{};
 return <section className="report-view"><div className="actions report-actions"><button className="back" onClick={onClose}>Voltar</button><button disabled={busy||!blob} onClick={open}>Prévia do PDF</button><button disabled={busy||!blob} onClick={download}>Salvar PDF</button><button disabled={busy||!blob} onClick={print}>Imprimir</button></div>{busy&&<p role="status">Preparando PDF…</p>}{error&&<p className="error" role="alert">{error}</p>}<article className="report-paper"><div className="document-brand">{info.logo&&<img src={info.logo} alt={model.salao}/>}<div><h2>{model.salao}</h2>{info.slogan?.trim()&&<p className="document-slogan">{info.slogan}</p>}<p>{info.endereco}<br/>{[info.cnpj&&`CNPJ: ${info.cnpj}`,info.telefone,info.email].filter(Boolean).join(' · ')}</p></div></div><h1>{model.title}</h1><p className="document-date">{model.subtitle}</p>{model.sections.map((s,i)=><section className={s.pageBreakBefore?'document-separate':''} key={i}><h2>{s.title}</h2><div className="report-table-scroll"><table><thead><tr>{s.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{s.rows.length?s.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={s.headers.length}>Nenhum registro no período.</td></tr>}</tbody></table></div></section>)}</article></section>
}
